# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bytedance/Documents/course-master/cpp_6.824

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bytedance/Documents/course-master/cpp_6.824

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bytedance/Documents/course-master/cpp_6.824/CMakeFiles /Users/bytedance/Documents/course-master/cpp_6.824//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bytedance/Documents/course-master/cpp_6.824/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mrseq

# Build rule for target.
mrseq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrseq
.PHONY : mrseq

# fast build rule for target.
mrseq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrseq.dir/build.make CMakeFiles/mrseq.dir/build
.PHONY : mrseq/fast

#=============================================================================
# Target rules for targets named mrcooridnator

# Build rule for target.
mrcooridnator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrcooridnator
.PHONY : mrcooridnator

# fast build rule for target.
mrcooridnator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrcooridnator.dir/build.make CMakeFiles/mrcooridnator.dir/build
.PHONY : mrcooridnator/fast

#=============================================================================
# Target rules for targets named mrworker

# Build rule for target.
mrworker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrworker
.PHONY : mrworker

# fast build rule for target.
mrworker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrworker.dir/build.make CMakeFiles/mrworker.dir/build
.PHONY : mrworker/fast

#=============================================================================
# Target rules for targets named mrapps

# Build rule for target.
mrapps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrapps
.PHONY : mrapps

# fast build rule for target.
mrapps/fast:
	$(MAKE) $(MAKESILENT) -f mrapps/CMakeFiles/mrapps.dir/build.make mrapps/CMakeFiles/mrapps.dir/build
.PHONY : mrapps/fast

#=============================================================================
# Target rules for targets named libs

# Build rule for target.
libs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs
.PHONY : libs

# fast build rule for target.
libs/fast:
	$(MAKE) $(MAKESILENT) -f libs/CMakeFiles/libs.dir/build.make libs/CMakeFiles/libs.dir/build
.PHONY : libs/fast

#=============================================================================
# Target rules for targets named gflags_nothreads_static

# Build rule for target.
gflags_nothreads_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gflags_nothreads_static
.PHONY : gflags_nothreads_static

# fast build rule for target.
gflags_nothreads_static/fast:
	$(MAKE) $(MAKESILENT) -f third_party/gflags/CMakeFiles/gflags_nothreads_static.dir/build.make third_party/gflags/CMakeFiles/gflags_nothreads_static.dir/build
.PHONY : gflags_nothreads_static/fast

src/mrcoordinator.o: src/mrcoordinator.cpp.o
.PHONY : src/mrcoordinator.o

# target to build an object file
src/mrcoordinator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrcooridnator.dir/build.make CMakeFiles/mrcooridnator.dir/src/mrcoordinator.cpp.o
.PHONY : src/mrcoordinator.cpp.o

src/mrcoordinator.i: src/mrcoordinator.cpp.i
.PHONY : src/mrcoordinator.i

# target to preprocess a source file
src/mrcoordinator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrcooridnator.dir/build.make CMakeFiles/mrcooridnator.dir/src/mrcoordinator.cpp.i
.PHONY : src/mrcoordinator.cpp.i

src/mrcoordinator.s: src/mrcoordinator.cpp.s
.PHONY : src/mrcoordinator.s

# target to generate assembly for a file
src/mrcoordinator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrcooridnator.dir/build.make CMakeFiles/mrcooridnator.dir/src/mrcoordinator.cpp.s
.PHONY : src/mrcoordinator.cpp.s

src/mrsequential.o: src/mrsequential.cpp.o
.PHONY : src/mrsequential.o

# target to build an object file
src/mrsequential.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrseq.dir/build.make CMakeFiles/mrseq.dir/src/mrsequential.cpp.o
.PHONY : src/mrsequential.cpp.o

src/mrsequential.i: src/mrsequential.cpp.i
.PHONY : src/mrsequential.i

# target to preprocess a source file
src/mrsequential.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrseq.dir/build.make CMakeFiles/mrseq.dir/src/mrsequential.cpp.i
.PHONY : src/mrsequential.cpp.i

src/mrsequential.s: src/mrsequential.cpp.s
.PHONY : src/mrsequential.s

# target to generate assembly for a file
src/mrsequential.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrseq.dir/build.make CMakeFiles/mrseq.dir/src/mrsequential.cpp.s
.PHONY : src/mrsequential.cpp.s

src/mrworker.o: src/mrworker.cpp.o
.PHONY : src/mrworker.o

# target to build an object file
src/mrworker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrworker.dir/build.make CMakeFiles/mrworker.dir/src/mrworker.cpp.o
.PHONY : src/mrworker.cpp.o

src/mrworker.i: src/mrworker.cpp.i
.PHONY : src/mrworker.i

# target to preprocess a source file
src/mrworker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrworker.dir/build.make CMakeFiles/mrworker.dir/src/mrworker.cpp.i
.PHONY : src/mrworker.cpp.i

src/mrworker.s: src/mrworker.cpp.s
.PHONY : src/mrworker.s

# target to generate assembly for a file
src/mrworker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrworker.dir/build.make CMakeFiles/mrworker.dir/src/mrworker.cpp.s
.PHONY : src/mrworker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gflags_nothreads_static"
	@echo "... libs"
	@echo "... mrapps"
	@echo "... mrcooridnator"
	@echo "... mrseq"
	@echo "... mrworker"
	@echo "... src/mrcoordinator.o"
	@echo "... src/mrcoordinator.i"
	@echo "... src/mrcoordinator.s"
	@echo "... src/mrsequential.o"
	@echo "... src/mrsequential.i"
	@echo "... src/mrsequential.s"
	@echo "... src/mrworker.o"
	@echo "... src/mrworker.i"
	@echo "... src/mrworker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

